# Generated by Django 4.2.30 on 2026-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='avg_cost_gbp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_text',
            field=models.TextField(),
        ),
    ]
