# Generated by Django 4.2.30 on 2026-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_savedcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcar',
            name='last_diagnosis',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='savedcar',
            name='last_problem_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
